### ISSUE TITLE
Error in submission

### ISSUE THREAD

**Issue by aledotgomez** [rgoomar/contactform#2]
Installed package, placed in the template and added the necessary server code. When I submit the form, i states " Error! Please check your inputs!" and in developer tools, "Error: JSON.stringify cannot serialize cyclic structures." 

Is this perhaps due to this message: 
"Warning: Assigning helper with `Template.contactForm.formSubmitted = ...` is deprecated.  Use `Template.contactForm.helpers(...)` instead."

I really like this package and just hope it can work correctly. Thanks!

**Comment by rgoomar** [comment]
I replicated the issue and it should be fixed now. Published a new version. :)

**Comment by aledotgomez** [comment]
Re-installed it. It solves the issue now. However, I get the following error when trying to send: " Error! Please check your inputs!" 

I think this might be related to the mail environment variable that I haven't put in successfully yet. How did  you format your mail environment variable?

I placed mine under mail.js

Meteor.startup(function () {
  process.env.MAIL_URL = 'smtp://postmaster%40meteorize.mailgun.org:(email goes here)@smtp.mailgun.org:587';
});

Thanks a lot!

**Comment by rgoomar** [comment]
It's possible that it's related to your `MAIL_URL` environment variable. Are you seeing any mail errors in the server logs?

Also, it could potentially be the `%40` that's included in your string that could be causing issues, but i'm not entirely sure.
