### ISSUE TITLE
Dropdown problem after meteor update

### ISSUE THREAD

**Issue by chieina** [rgoomar/contactform#3]
after an update, the ian:accounts-ui-bootstrap-3 no longer pops out the login dropdown form

**Comment by chieina** [comment]
as a temporary fix, added this to:

if( $("#login-dropdown-list").hasClass("open") ){
        $("#login-dropdown-list").removeClass("open");  
      }else{
        $("#login-dropdown-list").addClass("open");  
      }

**Comment by rgoomar** [comment]
@chieina There is no dropdown being used in the contact form. This would be in the repository that is using that.

**Comment by chieina** [comment]
![sign_in_join](https://cloud.githubusercontent.com/assets/3444151/9566714/8e57f39e-4f42-11e5-9ab7-703fd3106e6c.jpg)

Hi,

Yes there is no dropdown in the contacts form but it affects the dropdown in the ian:accounts-ui-bootstrap-3. Please see screenshot. I tested it by removing the contactform and it worked fine. The dropdown worked but I needed the contactform that is why I added the code below:

if( $("#login-dropdown-list").hasClass("open") ){
$("#login-dropdown-list").removeClass("open");

}else{
$("#login-dropdown-list").addClass("open");

}

I need the contactform and the login form
